apiVersion: serving.knative.dev/v1
kind: Service
metadata:
      name: my-service
      annotations:
        run.googleapis.com/ingress: internal
        run.googleapis.com/cpu-throttling: 'False'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '2'
        autoscaling.knative.dev/maxScale: '50'
    spec:
      containers:
        resources:
          limits:
            cpu: '2'
