apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: my-service
spec:
  template:
    spec:
      template:
        metadata:
          annotations:
            autoscaling.knative.dev/maxScale: '10'
