on:
  push:
    branches:
    - main
    
jobs:
  container-build-push-deploy:
    name: Build Container Push to Registry Deploy to Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: us-docker.pkg.dev/cloudrun/container/hello@sha256:42517c698aef1d7105a332c41381b37ce81aaafe0486a8aaf0b0d79e38b0356f
      PROJECT_ID: test-darwin-328107
      REGION: us-central1
    steps:
    - name: Authenticate With GCP
      id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
    
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: my-service
        image: us-docker.pkg.dev/cloudrun/container/hello@sha256:42517c698aef1d7105a332c41381b37ce81aaafe0486a8aaf0b0d79e38b0356f
        region: ${{ env.REGION }}
        metadata: ~/service.yaml

          

       
